### ISSUE TITLE
misbehave for sample-upload with files > 18Mb

### ISSUE THREAD

**Issue by Ma-Shell** [HolmesProcessing/Holmes-Gateway#26]
if the file is larger than 18Mb, the master-gateway reads the username as empty and authentication fails

**Comment by webstergd** [comment]
is this fixed by #28

**Comment by Ma-Shell** [comment]
Yes and no. The new limit should be at 200 mb. However, at the moment, master-gateway won't tell you that the file is too big, but rather indicate that the user was not authenticated. I'll fix the latter part later, but there must be a limit. (Should probably make it a configuration setting instead of hardcoding it, though)
